workflow:
  rules:
    # run job if pushed a tag
    - if: '$CI_COMMIT_TAG'

stages:
  - build
  - test

variables:
  # CI Registry Repository
  CI_REGISTRY_REPO: "docker.io/arogov/gcc-arm-make-alpine"
  # Shell print color codes
  OK_COL_CODE: '\e[0m'
  ERR_COL_CODE: '\e[31m'

build:
  stage: build
  rules:
    # run job if pushed a tag
    - if: '$CI_COMMIT_TAG'
  tags:
    - shared
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # Build
    - >
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile 
      --build-arg TOOLCHAIN_TAR_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 
      --destination "$CI_REGISTRY_REPO:$CI_COMMIT_TAG" # --destination "$CI_REGISTRY_REPO:latest"

test:version:
  stage: test
  rules:
    # run job if pushed a tag
    - if: '$CI_COMMIT_TAG'
  tags:
    - shared
  image:
    name: "$CI_REGISTRY_REPO:$CI_COMMIT_TAG"
    entrypoint: [""]
  script:
    - |-
      if ! arm-none-eabi-gcc --version; then
        echo -e "${ERR_COL_CODE}Error running arm-none-eabi-gcc${OK_COL_CODE}"
        exit 1
      fi
